# This rule is not used by the project crdify itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the ansible.crdify.sh.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: crdify
    app.kubernetes.io/managed-by: kustomize
  name: ansiblejob-editor-role
rules:
- apiGroups:
  - ansible.crdify.sh
  resources:
  - ansiblejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ansible.crdify.sh
  resources:
  - ansiblejobs/status
  verbs:
  - get
